version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=application
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root@postgres
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local